AWSTemplateFormatVersion: "2010-09-09"
Description: Main control plane template that includes IAM, S3, and ECS nested stacks.

Parameters:

  BaseTemplateURL:
    Type: String
    Description: The root URL for CloudFormation templates

  TokenSecretARN:
    Type: String
    Description: AWS Secrets Manager Plaintext secret ARN of the stored control plane token.
    NoEcho: true

  Name:
    Type: String
    Description: The base name for resources.

  Description:
    Type: String
    Description: Description of the control plane.
    Default: My AWS control plane description

  SubnetIDs:
    Type: String
    Description: The list of subnet IDs for the ECS service.

  SecurityGroupIDs:
    Type: String
    Description: The list of security group IDs for the ECS service.

  Image:
    Type: String
    Description: The Docker image for the control-plane container.
    Default: "gatlingcorp/control-plane:latest"

  Command:
    Type: String
    Description: The command to run in the control-plane container.
    Default: ""

  Locations:
    Type: String
    Description: A list of location configurations (as JSON strings).

  PrivatePackage:
    Type: String
    Description: The S3 bucket name containing the configuration file.
    Default: "{}"

  CloudWatchLogs:
    Type: String
    AllowedValues: ["true", "false"]
    Description: Indicates if CloudWatch Logs are enabled.
    Default: "true"
  
  UseECR:
    Type: String
    AllowedValues: ["true", "false"]
    Description: Indicates if ECR IAM permissions should be created.
    Default: "false"

Resources:

  IAMStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "${BaseTemplateURL}/control-plane/templates/iam/template.yaml"
      Parameters:
        Name: !Sub "${Name}-role"
        TokenSecretARN: !Ref TokenSecretARN
        PrivatePackage: !Ref PrivatePackage
        CloudWatchLogs: !Ref CloudWatchLogs
        UseECR: !Ref UseECR

  ECSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "${BaseTemplateURL}/control-plane/templates/ecs/template.yaml"
      Parameters:
        ECSTaskRoleARN: !GetAtt IAMStack.Outputs.ECSTaskRoleARN
        TokenSecretARN: !Ref TokenSecretARN
        Name: !Ref Name
        Description: !Ref Description
        SubnetIDs: !Ref SubnetIDs
        SecurityGroupIDs: !Ref SecurityGroupIDs
        Image: !Ref Image
        Command: !Ref Command
        Locations: !Ref Locations
        PrivatePackage: !Ref PrivatePackage
        CloudWatchLogs: !Ref CloudWatchLogs
