{{- if and (.Values.privatePackage.enabled) (eq .Values.privatePackage.repository.type "filesystem") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.controlPlane.name }}-pvc"
  namespace: "{{ .Values.namespace }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  storageClassName: {{ .Values.privatePackage.persistentVolumeClaim.storageClassName }}
  volumeMode: {{ .Values.privatePackage.persistentVolumeClaim.volumeMode }}
  {{- if .Values.privatePackage.persistentVolumeClaim.selector }}
  selector:
    {{ toYaml .Values.privatePackage.persistentVolumeClaim.selector | nindent 4 }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.privatePackage.persistentVolumeClaim.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.privatePackage.persistentVolumeClaim.storage }}
{{- end }}
