apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.controlPlane.name }}-service-account"
  namespace: "{{ .Values.namespace }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
