{{- if .Values.controlPlane.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.controlPlane.serviceAccount.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
  {{- if .Values.controlPlane.AWSroleARN }}
    eks.amazonaws.com/role-arn: "{{ .Values.controlPlane.AWSroleARN }}"
  {{ end }}
  {{- if .Values.controlPlane.AzureClientID }}
    azure.workload.identity/client-id: "{{ .Values.controlPlane.AzureClientID }}"
  {{ end }}
  {{- if .Values.controlPlane.GCPServiceAccount }}
    iam.gke.io/gcp-service-account: "{{ .Values.controlPlane.GCPServiceAccount }}"
  {{ end }}
{{ end -}}
