apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Values.controlPlane.name }}-service-account"
  namespace: "{{ .Values.namespace }}"
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
  {{- if .Values.controlPlane.AWSroleARN }}
    eks.amazonaws.com/role-arn: "{{ .Values.controlPlane.AWSroleARN }}"
  {{ end }}
  {{- if .Values.controlPlane.AzureClientID }}
    azure.workload.identity/client-id: "{{ .Values.controlPlane.AzureClientID }}"
  {{ end }}
