AWSTemplateFormatVersion: "2010-09-09"
Description: Template to define the location data.

Parameters:

  Id:
    Type: String
    Description: Identifier for the location.

  Description:
    Type: String
    Description: Description of the location.
    Default: "Private Location on AWS"

  Region:
    Type: String
    Description: AWS region for the location.
    Default: "eu-west-3"

  SubnetIDs:
    Type: String
    Description: Comma-separated list of subnet IDs.

  SecurityGroupIDs:
    Type: String
    Description: Comma-separated list of security group IDs.

  Spot:
    Type: String
    AllowedValues: ["true", "false"]
    Description: Whether to use spot instances.
    Default: "false"

  ElasticIPs:
    Type: String
    Description: List of Elastic IP addresses.
    Default: "[]"

  AMItype:
    Type: String
    Description: AMI type.
    Default: "certified"

  Engine:
    Type: String
    Description: Engine type.
    Default: "classic"

  JavaVersion:
    Type: String
    Description: Java version.
    Default: "latest"

  InstanceType:
    Type: String
    Description: EC2 instance type.
    Default: "c7i.xlarge"

  ProfileName:
    Type: String
    Description: Profile name.
    Default: ""

  IAMInstanceProfile:
    Type: String
    Description: IAM instance profile name.
    Default: ""

  Tags:
    Type: String
    Description: JSON-formatted string of tags.
    Default: "{}"

  TagsFor:
    Type: String
    Description: JSON-formatted string of tags for specific resources.
    Default: "{}"

  SystemProperties:
    Type: String
    Description: JSON-formatted string of tags for specific resources.
    Default: "{}"

  JavaHome:
    Type: String
    Description: Java home path.
    Default: "/usr/lib/jvm/zulu"

  JvmOptions:
    Type: String
    Description: List of JVM options.
    Default: "[]" 

Resources:

  DummyResource:
    Type: "AWS::CloudFormation::WaitConditionHandle"

Outputs:

  Conf:
    Description: "Combined location data as a JSON string."
    Value: !Sub |
      {
        "type": "aws",
        "id": "${Id}",
        "description": "${Description}",
        "region": "${Region}",
        "subnets": ${SubnetIDs},
        "security-groups": ${SecurityGroupIDs},
        "instance-type": "${InstanceType}",
        "spot": ${Spot},
        "ami": {
          "type": "${AMItype}",
          "java": "${JavaVersion}"
        },
        "engine": "${Engine}",
        "elastic-ips": ${ElasticIPs},
        "tags": ${Tags},
        "tags-for": ${TagsFor},
        "profile_name": "${ProfileName}",
        "iam-instance-profile": "${IAMInstanceProfile}",
        "system-properties": ${SystemProperties},
        "java-home": "${JavaHome}",
        "jvm-options": ${JvmOptions}
      }
