name: Lint & Test

on:
  push:
    branches:
      - main
    paths:
      - 'helm-chart/**'
  pull_request:
    branches:
      - main
    paths:
      - 'helm-chart/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Lint Helm Chart
        working-directory: helm-chart
        run: helm lint .

      - name: Validate Helm Templates
        working-directory: helm-chart
        run: helm template . --debug

    outputs:
      lint_status: success
