name: Package

on:
  workflow_run:
    workflows: ["Lint & Test"]
    types:
      - completed

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Package Helm chart
        working-directory: helm-chart
        run: |
          OUTPUT=$(helm package .)
          CHART_FILE=$(echo "$OUTPUT" | awk '/Successfully packaged chart and saved it to:/{print $NF}')
          echo "CHART_FILE=$CHART_FILE" >> $GITHUB_ENV 

    outputs:
      chart_file: ${{ env.CHART_FILE }}
